import { TRANSLATION_KEYS } from '@/shared/lib/i18n/translationKeys';

export const GENDER_TYPES = {
  FEMALE: 'female',
  MALE: 'male',
  CUSTOM: 'custom',
  PREFER_NOT_TO_SAY: 'prefer_not_to_say',
} as const;

export type GenderType = (typeof GENDER_TYPES)[keyof typeof GENDER_TYPES];

export interface GenderOption {
  key: GenderType;
  labelKey: TRANSLATION_KEYS;
}

export const GENDER_TRANSLATION_MAP: Record<GenderType, TRANSLATION_KEYS> = {
  [GENDER_TYPES.FEMALE]: TRANSLATION_KEYS.PROFILE_GENDER_FEMALE,
  [GENDER_TYPES.MALE]: TRANSLATION_KEYS.PROFILE_GENDER_MALE,
  [GENDER_TYPES.CUSTOM]: TRANSLATION_KEYS.PROFILE_GENDER_CUSTOM,
  [GENDER_TYPES.PREFER_NOT_TO_SAY]: TRANSLATION_KEYS.PROFILE_GENDER_PREFER_NOT_TO_SAY,
};

export const GENDER_OPTIONS: GenderOption[] = [
  { key: GENDER_TYPES.FEMALE, labelKey: TRANSLATION_KEYS.PROFILE_GENDER_FEMALE },
  { key: GENDER_TYPES.MALE, labelKey: TRANSLATION_KEYS.PROFILE_GENDER_MALE },
  { key: GENDER_TYPES.CUSTOM, labelKey: TRANSLATION_KEYS.PROFILE_GENDER_CUSTOM },
  { key: GENDER_TYPES.PREFER_NOT_TO_SAY, labelKey: TRANSLATION_KEYS.PROFILE_GENDER_PREFER_NOT_TO_SAY },
];
