export const palette = {
  bluePrimary: '#0095F6',
  bluePressed: '#1877F2',
  blueDisabled: '#0095F680',
  redError: '#ED4956',
  greenSuccess: '#00BA88',
  white: '#FFFFFF',
  black: '#000000',
  gray800: '#262626',
  gray700: '#363636',
  facebookBlue: '#1877F2',
  transparent: 'transparent',
};

export const lightColors = {
  bgPrimary: '#FFFFFF',
  bgSecondary: '#FAFAFA',
  surface: '#FFFFFF',
  border: '#DBDBDB',
  borderFocus: palette.bluePrimary,
  textPrimary: '#262626',
  textSecondary: '#737373',
  textLink: palette.bluePrimary,
  actionPrimary: palette.bluePrimary,
  actionPrimaryDisabled: '#B2DFFC',
  actionSecondaryText: palette.facebookBlue,
  error: palette.redError,
  success: palette.greenSuccess,
  divider: '#DBDBDB',
  toastBg: palette.gray800,
  toastText: palette.white,
  bottomSheetHandleBar: '#C7C7CC',
  backdropColor: '#000000',
  backdropOverlay: 'rgba(0, 0, 0, 0.4)',
  avatarShimmer: '#E1E1E1',
  shimmerHighlight: '#F5F5F5',
  dialogBg: '#FFFFFF',
};

export const darkColors = {
  bgPrimary: '#000000',
  bgSecondary: '#121212',
  surface: '#121212',
  border: '#262626',
  borderFocus: palette.bluePrimary,
  textPrimary: '#F5F5F5',
  textSecondary: '#A8A8A8',
  textLink: '#3797EF',
  actionPrimary: palette.bluePrimary,
  actionPrimaryDisabled: '#002D4A',
  actionSecondaryText: palette.facebookBlue,
  error: palette.redError,
  success: palette.greenSuccess,
  divider: '#262626',
  toastBg: palette.gray700,
  toastText: palette.white,
  bottomSheetHandleBar: '#545458',
  backdropColor: '#000000',
  backdropOverlay: 'rgba(0, 0, 0, 0.6)',
  avatarShimmer: '#262626',
  shimmerHighlight: '#383838',
  dialogBg: '#262626',
};


export type ThemeColors = typeof lightColors;
